blog/urls.py
from django.urls import path
# from . import views
from .views import *

urlpatterns = [
    path('', ProductListView.as_view(), name='blog-home'),
    # path('tag/?P<slug>[가-힣a-zA-Z]/', PostListByTag.as_view(), name='item_in_tag'),
    # path('tag/<slug:slug>/', PostListByTag.as_view(), name='item_in_tag'),
    # path('category/<slug:slug>/', PostListByCategory.as_view(), name='item_in_category'),
    # path('category/<slug:category_slug>/', views.item_in_category, name='item_in_category'),
    path('category/<slug>/', ProductListByCategory.as_view(), name='item_in_category'),
    path('product/<int:id>/<slug>/', product_detail, name='product-detail'),
    # path('product/<int:id>/<slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:id>/<slug>/qna/', product_qna, name='product-qna'),
    path('product/new/', ProductCreateView.as_view(), name='product-create'),
    path('product/<int:id>/<slug>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:id>/<slug>/delete/', product_delete, name='product-delete'),
    path('seller/<int:id>/', list_by_seller, name='list-by-seller'),
]

# pattern(s) tried: ['category\\/(?P<slug>[-a-zA-Z0-9_]+)\\/$']

# /^[가-힣a-zA-Z]+$/
#
# ?P<year>[0-9]{4})/$
#
# (?P<year>[0-9]{4})

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<int:product_id>/', remove, name='product_remove'),

]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class AddProductForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.HiddenInput)
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from blog.models import Product
from .forms import AddProductForm
from .cart import Cart


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    # print(product.title) //ok

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

        return redirect('cart:detail')


def detail(request):
    cart = Cart(request)

    for product in cart:
        product['quantity_form'] = AddProductForm(
            initial={'quantity': product['quantity'], 'is_update': True}
        )
    return render(request, 'cart/detail.html', {'cart': cart})


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

cart/templates/cart/detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col" class="text-center">Image</th>
        <th scope="col" class="text-center">상품명</th>
        <th scope="col" class="text-center">수량</th>
        <th scope="col" class="text-center">가격</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <th scope="row" class="text-center">
            <a href="{{ item.product.get_absolute_url }}">
                <img src="{{ item.product.image.url }}" class="img-thumbnail"
                     style="width:40px;height:40px">
            </a>
        </th>
        <td class="text-center">{{ item.product.title }}</td>
        <td style="width:30$" class="text-center">
            <form action="{% url 'cart:product_add' item.product.id %}" method="post">
                <input type="number" name="quantity" style="width:50px;"
                       value="{{item.quantity_form.quantity.value}}">

                {{ item.quantity_form.is_update }}
                <input type="submit" class="btn btn-primary btn-sm" value="수정">
                {% csrf_token %}
                <a class="btn btn-danger btn-primary btn-sm" href="{% url 'cart:product_remove' item.product.id %}">삭제</a>

            </form>
        </td>
        <td class="num text-right">{{ item.total_price }} 원</td>

    </tr>
    {% endfor %}
    <tr class="total">
        <td id="cart_total">Total</td>
        <td colspan="2"></td>
        <td class="num text-right">{{ cart.get_product_total }} 원</td>
    </tr>

    </tbody>
</table>

{% endblock %}