blog/urls.py
from django.urls import path
# from . import views
from .views import *

urlpatterns = [
    path('', ProductListView.as_view(), name='blog-home'),
    # path('tag/?P<slug>[가-힣a-zA-Z]/', PostListByTag.as_view(), name='item_in_tag'),
    # path('tag/<slug:slug>/', PostListByTag.as_view(), name='item_in_tag'),
    # path('category/<slug:slug>/', PostListByCategory.as_view(), name='item_in_category'),
    # path('category/<slug:category_slug>/', views.item_in_category, name='item_in_category'),
    path('category/<slug>/', ProductListByCategory.as_view(), name='item_in_category'),
    path('product/<int:id>/<slug>/', product_detail, name='product-detail'),
    # path('product/<int:id>/<slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:id>/<slug>/qna/', product_qna, name='product-qna'),
    path('product/new/', ProductCreateView.as_view(), name='product-create'),
    path('product/<int:id>/<slug>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:id>/<slug>/delete/', product_delete, name='product-delete'),
    path('seller/<int:id>/', list_by_seller, name='list-by-seller'),
]

# pattern(s) tried: ['category\\/(?P<slug>[-a-zA-Z0-9_]+)\\/$']

# /^[가-힣a-zA-Z]+$/
#
# ?P<year>[0-9]{4})/$
#
# (?P<year>[0-9]{4})

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<int:product_id>/', remove, name='product_remove'),

]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return 'tag/{}/'.format(self.slug)


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('item_in_category', args=[self.slug])


class Product(models.Model):
    title = models.CharField(verbose_name='상품명', max_length=100)
    image = models.ImageField(verbose_name='상품이미지', upload_to="photo", default='default.jpg')
    slug = models.SlugField(max_length=200, db_index=True, unique=True,
                            allow_unicode=True, null=True)
    price = models.DecimalField(verbose_name='정가', max_digits=10, decimal_places=0, null=True)
    discount_price = models.DecimalField(verbose_name='할인가', max_digits=10, decimal_places=0, null=True, blank=True)
    content = models.TextField(verbose_name='상품설명')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    # tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product-detail', args=[self.id, self.slug])


class Qna(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    reply = models.ForeignKey('Qna', null=True, related_name='replies', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text

blog/forms.py
from .models import Qna
from django import forms
from django.forms import Textarea


class QnaForm(forms.ModelForm):
    # text = forms.CharField(label="", widget=forms.TextArea(attrs={'cols':5, 'rows':3}))

    class Meta:
        model = Qna
        fields = ['text']
        widgets = {
            'text': Textarea(attrs={'cols':5,
                                    'rows':3,
                                    'placeholder': '내용을 입력해주세요',
                                    }
                             )
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from django.contrib.auth.models import User
from .models import Product, Category, Qna, Tag
from cart.forms import AddProductForm
from .forms import QnaForm


def list_by_seller(request, id):
    seller = User.objects.get(id=id)
    items = Product.objects.filter(author=seller)
    context = {'items': items, 'seller': seller}
    return render(request, 'blog/list_by_seller.html', context)
    # print("id", id)



# def item_in_category(request, category_slug=None):
#
#     current_category = None
#     categories = Category.objects.all()
#     items = Post.objects.all()
#
#     if category_slug:
#         current_category = get_object_or_404(Category, slug=category_slug)
#         items = items.filter(category=current_category)
#
#     context = {
#         'current_category': current_category,
#         'category_list': categories,
#         'items': items
#     }
#     return render(request, 'blog/home.html', context)


# def item_in_tag(request, tag_slug=None):
#     if tag_slug:
#         items = tag_slug.post_set.order_by('-date_posted')
#     else:
#         items = Post.objects.all()
#
#     context = {
#         'items': items
#     }
#     return render(request, 'blog/home.html', context)


class ProductListView(ListView):
    model = Product
    template_name = 'blog/home.html'
    context_object_name = 'products'
    product_total = Product.objects.all().count()
    print("product_total : ", product_total)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()

        return context
    # context = {
    #     'posts': Post.objects.all(),
    #     'category_list': Category.objects.all()
    #
    # }
    # ordering = ['-date_posted']


class ProductListByCategory(ProductListView):

    def get_queryset(self):
        slug = self.kwargs['slug']
        # print("slug")
        # print(slug)
        category = Category.objects.get(slug=slug)
        return Product.objects.filter(category=category).order_by('-date_posted')


# class PostListByTag(ListView):
#     print('PostListByTag 실행')
#     model = Post
#     template_name = 'blog/home.html'
#     context_object_name = 'posts'
#
#     def get_queryset(self):
#         print('PostListByTag getqueryset 실행')
#
#         slug = self.kwargs['slug']
#         print("slug")
#         print(slug)
#         tag = Tag.objects.get(slug=slug)
#         return tag.post_set.order_by('-date_posted')
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super(PostListByTag, self).get_context_data(**kwargs)
#         context['category_list'] = Category.objects.all()
#
#         return context


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = '/'

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.author:
            return True
        return False


# class ProductDetailView(DetailView):
#     model = Product


def product_detail(request, id, slug=None):
    context = {}
    product = get_object_or_404(Product, id=id, slug=slug)
    context['add_to_cart'] = AddProductForm(initial={'quantity':1})
    context['q_form'] = QnaForm()
    context['product'] = product
    context['questions'] = product.qna_set.all().order_by('-created')

    return render(request, 'blog/product_detail.html', context)


def product_delete(request, id, slug=None):
    product = Product.objects.get(id=id)
    if product.author != request.user:
        return render(request, 'blog/forbidden.html')

    if request.method == 'POST':
        Product.objects.filter(id=id).delete()
        return redirect('/')
    return render(request, 'blog/product_delete.html', {'product': product})

class ProductDetailView(DetailView):
    model = Product

def product_qna(request, slug, id):
    model = Qna
    product = Product.objects.get(id=id)

    if request.method == 'POST':
        q_form = QnaForm(request.POST)
        if q_form.is_valid():
            qna = q_form.save(commit=False)
            qna.product = product
            reply_id = request.POST.get('qna_id')
            text = request.POST.get('text')
            # print('reply_id : ', reply_id)
            # print('text : ', text)
            qna_qs = None
            if reply_id:
                qna_qs = Qna.objects.get(id=reply_id)
            qna = Qna.objects.create(product=product, text=text, author=request.user, reply=qna_qs)
            qna.save()
            return redirect('product-detail', id=id, slug=slug)
        return redirect('product-detail', id=id, slug=slug)
    else :
        return render(request, 'blog/forbidden.html')



class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['title', 'content', 'image', 'price', 'discount_price', 'category']

    def form_valid(self, form):
        form.instance.slug = form.instance.title.replace(' ', '-')
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    fields = ['title', 'content', 'image', 'price', 'discount_price']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.author:
            return True
        return False

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Django Market</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <!-- Bootstrap core CSS -->
<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/shoptemplate.css' %}">
<style>

li {list-style-type: none;}
#top-nav-box {
  /* position: absolute;
  right: 0; */
  display: inline-block;
  float: right;
}
#top-nav-box > ul{
  display:flex; flex-direction: row; margin:0 10px; font-size: 15px;
}
#top-nav-box > ul > li > a{
  color:#fff;
}
#nav-wrap
#main_logo{
  float:left; color:gray;
}
/* #top-nav *{
  outline:1px solid green
} */

</style>

</head>

<body>

<nav class="bg-dark fixed-top" style="border-radius: 0" id="top-nav">

    <div class="container" id="nav-wrap" style="position:relative;">
      <span style="">
        <a class="" href="/" id="main_logo">Django Market</a>
      </span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="" id="top-nav-box">
            <ul class="">
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-item nav-link" href="{% url 'product-create' %}">업로드</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="/cart/">카트</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li>
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                </li>
              {% endif %}


            </ul>
        </div>
    </div>
</nav>

  <!-- Page Content -->
  <div class="container" style="padding-top:80px">

    {% block content %}
    {% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
<!--  <footer class="py-5 bg-dark">-->
<!--    <div class="container">-->
<!--      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>-->
<!--    </div>-->
<!--    &lt;!&ndash; /.container &ndash;&gt;-->
<!--  </footer>-->

  <!-- Bootstrap core JavaScript -->

  <link rel="stylesheet" type="text/css" href="{% static 'blog/js/jquery.min.js' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/js/bootstrap.bundle.min.js' %}">



</body>

</html>

blog/templates/blog/forbidden.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <h2>접근할 수 있는 권한이 없습니다</h2>
    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}

<div class="row">

      <div class="col-lg-2">

        <h4 class="my-4">카테고리</h4>
        <div class="list-group">
            <a href="/" class="list-group-item">All</a>
            {% for c in category_list %}
                <a href="{{c.get_absolute_url}}" class="list-group-item">
                    {{c.name}}
                </a>

            {% endfor %}
<!--          <a href="#" class="list-group-item">Category 2</a>-->
<!--          <a href="#" class="list-group-item">Category 3</a>-->
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-10">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
<!--          <div class="carousel-inner" role="listbox">-->
<!--            <div class="carousel-item active">-->
<!--              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">-->
<!--            </div>-->
<!--            <div class="carousel-item">-->
<!--              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">-->
<!--            </div>-->
<!--            <div class="carousel-item">-->
<!--              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">-->
<!--            </div>-->
<!--          </div>-->
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
    {% for product in products %}

          <div class="col-lg-4 col-md-6 mb-4" id="post-card-{{product.pk}}">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src="{{ product.image.url }}"></a>
              <div class="card-body">
                <h4 class="card-title">
<!--                        <p>product.id : {{ product.id }} </p>-->
<!--                        <p>product.slug : {{ product.slug }} </p>-->
                  <a href="{{product.get_absolute_url}}">{{ product.title }}</a>
                </h4>
                  {% if product.discount_price != None %}
                  <p class="article-title">
                    <span style="text-decoration:line-through;">
                        {{ product.price }}원</span> {{ product.discount_price }}원
                  </p>
                  {% else %}
                  <p>
                      {{product.price}} 원
                  </p>
                  {% endif %}
                  <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>-->

                  <div class="media-body">
                      <a class="mr-2 pl-2" href="{% url 'list-by-seller' product.author.id %}">
                          <img class="rounded-circle article-img" style="width:60px; height:60px;"
                            src="{{product.author.profile.image.url}}">
                      {{ product.author }}</a>
                      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                  </div>
              </div>
            </div>
          </div>

    {% endfor %}

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->



{% endblock content %}

blog/templates/blog/list_by_seller.html
{% extends "blog/base.html" %}
{% block content %}

<div class="row">

    <div class="media-body pt-3">
      <img class="rounded-circle article-img" style="width:60px; height:60px;"
       src="{{seller.profile.image.url}}">
      <span class="mr-2 pl-2">{{ seller.username }}</span>
      <p>{{ seller.email }}</p>
      <p>판매중인 상품 : {{ items.count }}</p>
  </div>


    <div class="row">
        {% for product in items %}

        <div class="col-lg-4 col-md-6 mb-4" id="post-card-{{product.pk}}">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="{{ product.image.url }}"></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <!--                        <p>product.id : {{ product.id }} </p>-->
                        <!--                        <p>product.slug : {{ product.slug }} </p>-->
                        <a href="{{product.get_absolute_url}}">{{ product.title }}</a>
                    </h4>
                    <p><span style="text-decoration:line-through">{{ product.price }}
                    </span>
                        {{product.discount_price}} 원
                    </p>
                    <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>-->

                    <small class="text-muted">{{ product.date_posted|date:"Y년 F d일" }}</small>

                </div>
            </div>
        </div>

        {% endfor %}

    </div>
    <!-- /.row -->

</div>
<!-- /.row -->



{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">포스팅 삭제</legend>
                <h2>포스트를 삭제하시겠습니까? {{object.title}}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">예, 삭제하겠습니다</button>
                <a class="btn btn-outline-secondary"
                   href="{% url 'post-detail' object.id %}">취소</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}



<article class="media content-section">
    <img class="rounded-circle article-img" style="width:60px; height:60px;"
         src="{{object.author.profile.image.url}}">


    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2" href="#">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
            {% if object.author == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb1" href="{% url 'post-update' object.id %}">수정</a>
                <a class="btn btn-danger btn-sm mt-1 mb1" href="{% url 'post-delete' object.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
        <div>
            <img src="{{ object.image.url }}">
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
        <p>Tags :&nbsp;
            {% for t in object.tags.all %}
                #{{ t }} &nbsp;
            {% endfor %}
        </p>
    </div>
    <div id="comment-list">

    </div>
</article>


{% endblock content %}

blog/templates/blog/post_detailbk.html
{% extends "blog/base.html" %}
{% block content %}



<article class="media content-section">
    <img class="rounded-circle article-img" style="width:60px; height:60px;"
         src="{{object.author.profile.image.url}}">


    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2" href="#">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
            {% if object.author == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb1" href="{% url 'post-update' object.id %}">수정</a>
                <a class="btn btn-danger btn-sm mt-1 mb1" href="{% url 'post-delete' object.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
        <div>
            <img src="{{ object.image.url }}">
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
        <p>Tags :&nbsp;
            {% for t in object.tags.all %}
                #{{ t }} &nbsp;
            {% endfor %}
        </p>
    </div>
    <div id="comment-list">

    </div>
</article>


{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">포스팅</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">완료</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/product_confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">포스팅 삭제</legend>
                <h2>포스트를 삭제하시겠습니까? {{object.title}}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">예, 삭제하겠습니다</button>
                <a class="btn btn-outline-secondary"
                   href="{% url 'post-detail' object.id %}">취소</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/product_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<article class="media content-section">
    <div class="media-body">
        <h3 class="article-title pt-3">{{ product.title }}</h3>
        {% if product.author == user %}
        <a class="btn btn-secondary btn-sm mt-1" href="./update">업데이트</a>
        <a class="btn btn-danger btn-sm mt-1" href="./delete">삭제</a>
        {% endif %}
        <div class="row pt-3">
            <div class="col-5">
                <img src="{{ product.image.url }}" width="100%">
            </div>
            <div class="col-7">
                {% if product.discount_price != None %}
                <p class="article-title" style="font-size:1.4em">
                    <span style="text-decoration:line-through;">
                        {{ product.price }}원</span> {{ product.discount_price }}원
                </p>
                {% else %}
                <p class="article-title" style="font-size:1.8em">
                    {{ product.price }}원
                </p>
                {% endif %}
                <p style="font-weight:bold font-size:1.5em"> 상세설명</p>


                <p class="article-content" style="font-size:1.3em">{{ product.content }}</p>
                <p class="text-muted">등록일 : {{ product.date_posted|date:"Y년 F d일" }}</p>
                {% if product.author != user%}
                <form action="{% url 'cart:product_add' product.id %}" method="post" class="pt-3">
                    {{ add_to_cart }}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary btn-sm" value="카트에 넣기">
                </form>
                {% endif %}
                <div class="article-metadata pt-4">
                    <a href="{% url 'list-by-seller' product.author.id %}">
                    <img class="rounded-circle article-img" style="width:60px; height:60px;"
                         src="{{product.author.profile.image.url}}">
                    {{ product.author }}</a>
                </div>
            </div>
        </div>

<!--        <p>Tags :&nbsp;-->
<!--            {% for t in object.tags.all %}-->
<!--                #{{ t }} &nbsp;-->
<!--            {% endfor %}-->
<!--        </p>-->
    </div>
</article>
<div id="qnaWrap">
    <div class="card my-4">
        <div class="card-body">
            <form action="{{product.get_absolute_url}}qna/" method="post">
                {% csrf_token %}
                {{ q_form|crispy }}
                <button type="submit" class="btn btn-primary">문의하기</button>
            </form>
        </div>
    </div>
    <p class="card-header">상품문의 ({{ product.qna_set.all.count }})</p>

    {% for q in questions %}
    <div class="card-body" style="border-bottom: 2px solid rgba(212,212,212,1)">
        <div class="media-body" style="font-size:1.3em;">
            <p>{{ q.text }}</p>
        </div>
        <p style="padding:10px 10px 5px"> by {{ q.author }}, {{ q.created|date:"Y년 F d일 h시 i분"  }}</p>
        {% if q.reply %}
        <p>답변 : {{q.reply.text}} <span>by {{q.reply.author}}, {{ q.reply.created|date:"Y년 F d일 h시 i분"  }}</span></p>
        {% endif %}

        {% if product.author == user %}
            <form action="{{product.get_absolute_url}}qna/" method="post">
                {% csrf_token %}

                <input type="hidden" name="qna_id" value="{{q.id}}">
                {{ q_form|crispy }}
                <button type="submit" class="btn btn-primary">답변하기</button>
            </form>

        {% endif %}
    </div>
    {% endfor %}
</div>

<!--<form method="post">-->
<!--    <input type="hidden" name="csrfmiddlewaretoken" value="W5vrhRLdFWDFnqiBvqbTGZ35NmIbfCcEHs8ObEnpGxmYflJaApLN0BITiIhq2HwI">-->
<!--    <input type="hidden" name="qna_id" value="1">-->


<!--    <div id="div_id_text" class="form-group">-->
<!--        <label for="id_text" class="col-form-label  requiredField">-->
<!--        Text<span class="asteriskField">*</span> </label>-->
<!--        <div class="">-->
<!--            <textarea name="text" cols="5" rows="3" placeholder="내용을 입력해주세요" class="textarea form-control form-control" required id="id_text">-->
<!--            </textarea>-->
<!--        </div>-->
<!--    </div>-->

<!--    <button type="submit" class="btn btn-primary">답변하기</button>-->
<!--</form>-->

{% endblock content %}